SELECT B.TITLE, B.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, TO_CHAR(R.CREATED_DATE, 'YYYY-MM-DD')
  FROM USED_GOODS_BOARD B JOIN USED_GOODS_REPLY R ON B.BOARD_ID = R.BOARD_ID
 WHERE B.CREATED_DATE BETWEEN TO_DATE('20221001', 'YYYYMMDD') AND TO_DATE('20221031 23:59:59', 'YYYYMMDD HH24:MI:SS')
 ORDER BY R.CREATED_DATE, B.TITLE